### ISSUE TITLE
HoverFly Goin Down while using Diff mode

### ISSUE THREAD

**Issue by chaitanya2829** [SpectoLabs/hoverfly#823] opened 2019-03-08 04:14 UTC
Hi Team,

I was using the diff mode in my hoverfly , and want to check the difference in responses in simulation against the real service , while i was doing the test in my machine - hoverfly is going down immediately when i use the diff mode.

Steps to replicate:

1)Captured the responses and altered the responses ( changed the data )
2) Now changed the mode to diff, and tried hitting the service...but hoverfly is going down immediately.

Can you please replicate the above steps and let me know the work around .Let me know if you need further details.

**Comment by tommysitu** [comment] 2019-03-08 08:29
@chaitanya2829, I can't reproduce this issue with diffing a simple API using Hoverfly `v1.0.0-rc.2`. 

Can you provide more details about the requests you are making please? And what changes did you make in the response?

**Comment by tommysitu** [comment] 2019-04-16 09:10
Closing as the issue is not reproducible. Please re-open if you need further help.

**Closed by tommysitu** 2019-04-16 09:10 UTC
Labels: more-info-needed
