### ISSUE TITLE
Route only few requests to middleware out of all virtualized

### ISSUE THREAD

**Issue by adisheshaiah** [SpectoLabs/hoverfly#645] opened 2017-08-14 08:01 UTC
Hi SpectoLabs Team
I am trying to benchmark Hoverfly for Performance. It is a great tool, and i have stubbed 13 REST APIs, and with little over 30mb memory consumption, and 30% cpu consumption (out of 4 cores of 2.0ghz) i was able to hit 600 TPS (Transactions Per Second), and response time was great below 10ms. Thanks for the tool.

Later i tried to do dynamic response by connecting to mysql db via python middleware. After this cpu consumption went upto 100%, and able to achieve 12 TPS only. This is mainly because multiple python exes are invoked, and they consumed a lot.
I noticed that each and every REST API being hitting via middleware. I require only 2 APIs responses to be dynamic. Can you please enhance hoverfly to have a flag in json file and go to middleware only for few requests instead of all.

Please let me know if you need any additional info.

Thanks
Adi G.

**Comment by JohnFDavenport** [comment] 2017-08-14 10:42
Yes, middleware requires a separate process so under a heavy load that is a fundamental limitation. Every OS we know imposes a very heavy overhead for creating, deleting and switching processes. So, we are planning to implement a more lightweight and scalable architecture for running ancillary functions - but with some restrictions. If you wish to know more feel free to contact me or @benjih .

**Comment by KvMadan** [comment] 2017-08-14 12:22
@JohnFDavenport @benjih 
In addition to what Adi requested above, it would be nice to have hoverfly launch only one instance of middleware (probably multi threaded) and respond to the requests where required from middleware.

**Comment by adisheshaiah** [comment] 2017-08-14 13:34
@JohnFDavenport  i require more details related to this (lightweight and scalable architecture for middleware). can you please send me the details to adisheshaiah@gmail.com

**Comment by mogronalol** [comment] 2017-08-14 13:59
@adisheshaiah Hoverfly supports HTTP middleware. This means you can start a HTTP server written in a lightweight language like Go or NodeJS, which will then be a long running process that handles requests and responses as they come in. This will solve your performance problems, and the documentation can be found here:

http://hoverfly.readthedocs.io/en/latest/pages/keyconcepts/middleware.html

I will now close this issue as this should resolve your problem. It is not a bug or a missing feature. However, if you do find a bug whilst trying it out, feel free to raise another issue GitHub. We are in the process of creating contribution guidelines to make this kind of thing clearer.

**Closed by mogronalol** 2017-08-14 13:59 UTC

**Comment by adisheshaiah** [comment] 2017-08-16 07:05
@mogronalol, can you please give any examples you have where request is going to Web Server from Hoverfly.
Previously i took python samples from you, and worked on top of that. Thanks for your help in advance. 
And also please do share contribution guidelines, i can help in Performance Testing of this tool.

**Comment by JohnFDavenport** [comment] 2017-08-17 13:33
We can provide more assistance on this matter if needed through a direct contact.
