### ISSUE TITLE
Incompatibility when proxying CORS/Ajax solution

### ISSUE THREAD

**Issue by paul-hammant** [SpectoLabs/hoverfly#368] opened 2017-02-03 09:54 UTC
To reproduce with the fantastic http://todobackend.com/ comparison portal's test harness:

```
git clone git@github.com:moredip/todo-backend-py.git 
cd todo-backend-py/
pip install web.py 
hoverctl start
hoverctl mode capture
python todo-backend.py 
```
In a browser, setup the proxy server to point to hoverfly. BUT change the excludes section. It probably says "don't proxy localhost". We don't want that, we want to hoverfly to explicitly record that. Instead we want to exclude the test harness from being captured - so change the 'don't-proxy' to be `todobackend.com` instead of `localhost`.

Then in the same browser window, open http://todobackend.com/specs/index.html?http://localhost:8080 to run the test harness.

Should take 2 seconds and be all 'green' suggesting that the test harness thinks the backend conforms to spec.

It isn't though - the thing takes a couple of minutes because of timeouts, and is a bunch of failing tests.

If you take out the browsers proxy changes (to facilitate hoverfly) then everything passes as expected.

Note: there are many tens of implementations on http://todobackend.com/ but the web.py one I chose doesn't need a database setup (it's doing it all in memory) and is therefore easy to use. Be aware though that the author set up web.py incorrectly, and you might need to find the python process in `ps aux` to kill it if control-c isn't responding.

**Comment by benjih** [comment] 2017-02-03 10:57
Hey @paul-hammant,

Follow the steps provided, I was unable to get todo-backend.py to pass against todobackend.com's test suite without introducing Hoverfly.

Could you possibly provide more information regarding todo-backend.py as I would been keen to see the suite passing against todo-backend.py before I start investigating this issue.

**Comment by paul-hammant** [comment] 2017-02-03 11:12
My bad - copy/paste error. Bug report above updated. Specifically

http://todobackend.com/specs/index.html?https://localhost:8080 changed to

http://todobackend.com/specs/index.html?http://localhost:8080

**Comment by benjih** [comment] 2017-02-03 11:35
Excellent, thanks @paul-hammant!

I am experiencing the same issues now. I will investigate and report back.

**Comment by benjih** [comment] 2017-02-03 12:29
Having looked into this issue, it turns out that during a refactor of the core architecture, POST and PUT requests being proxied forward do not contain their original request bodies. 

This bug only effects v0.10.0 of Hoverfly.

I will implement tests and fix as soon as possible. I will update this ticket when a new release has been published.

**Comment by paul-hammant** [comment] 2017-02-03 12:41
Yay!

**Comment by benjih** [comment] 2017-02-03 13:19
So I have fixed the issue with request bodies which is now on [fix-post-put-bodies](/SpectoLabs/hoverfly/tree/fix-post-put-bodies). 

Rerunning the todobackend test suite passed first time with Hoverfly capturing.

After switching Hoverfly to simulate mode and rerunning the test suite again resulted in a failure. Several of the test failures are about missing properties, incorrect lengths and several of the PATCH requests failed.

I will further investigate the PATCH request failures. Regarding the other failures, I believe these are due to stateful requests, which Hoverfly does not currently support.

**Comment by ph-ms** [comment] 2017-02-03 18:24
Sure there are stateful requests. I might take the recorded set into a 3GL of choice and morph it further until the test harness passes. 

Hoverfly can be reprogrammed with expectations between tests right?

**Comment by benjih** [comment] 2017-02-04 09:23
Currently, expectations are not within Hoverfly. Although, we are planning to introduce a validation API that will allow you to inspect Hoverfly after a test to determine whether certain requests have been made.

**Comment by paul-hammant** [comment] 2017-02-04 12:28
So don't you have all the expectations you need already? pseduocode:

```
test123() {
   when("/foo/bar/1").thenReply("text/json", "{ 'val':true }");
   performSomeInteractionOne();
   when("/foo/bar/1").thenReply(404);
   try {
       performSomeInteractionTwo();
       fail("should have barfed");
   } catch(404) {
      // expected
   }
}
```

**Comment by paul-hammant** [comment] 2017-02-04 12:44
Hey Benji - is there a chance you could record a video of you talking thru the stubbing of Pete's todomvc-backend?  It'd be 
1. here is the web.py version of todomvc working with the UI
2. here is the web-py version of todomvc working with the test-harness
3. here is the browser's reconfiguration to allow Hoverfly to capture
4. here is the captured traffic saved to a directory
5. here is a (naive) attempt to use that captured session to allow the test-harness to pass again, but
with no web.py todomvc-backend involved.
6. a short suggestion as to what the next steps to would be for a team that wanted to complete it.

It seems silly to use a test-harness to verify a mock, but there's some method to the madness - http://paulhammant.com/2015/12/17/more-on-technology-compatibility-kits-in-app-development/

**Comment by mogronalol** [comment] 2017-02-06 17:28
Correct me if I'm wrong, but the problem I see here is that we're recording stateful interactions:

So we do `GET http://localhost:8080/todo -> []`
Then later on we do `GET http://localhost:8080/todo -> [{"title":"walk the dog","id":2,"completed":false,"order":null,"url":"http://localhost:8080/todo/2"}]`

The problem is both requests are identical, so when we record one overrides the other. As of yet we can't think of an intelligent way to record this type of behaviour, but would be open to suggestions.

However, you can change the data (expectations) within Hoverfly whenever you want via an API call. This can also be orchestrated via the CLI or a language binding such as the one we have in Java. So if you were writing a test, you could change the data as you go along, just like your example.

**Comment by ph-ms** [comment] 2017-02-06 18:10
The capture mode, recording everything in a journal manner, wouldn't be useful for simulation mode reuse. But a programmable Hoverfly wouldn't care or know about the whole journal. One test or interaction at a time the testing logic (Java, C#, Python etc) would inform Hoverfly of the next set of expectations. The exported simulation, would have to show all the interactions, for it to be helpful, not a map/dict version with key uniqueness.

So, I'm asking for the 'simulation export' (subject to optional CLI args) to give the whole timeline.  And that there's also a 'programmable' mode, that takes only what it needs to respond next (which could easily be map/dict centric, as it's going to get reprogrammed constantly through the test suite.

**Comment by JohnFDavenport** [comment] 2017-02-07 08:50
It seems there may be some different use-cases and possibly some implicit performance NFRs here so we need to pick them apart and clarify.

**Comment by mogronalol** [comment] 2017-02-07 11:49
@ph-ms If you want to change the expectations during each test run you can do this using the Java language binding. Something like this:

```java
@ClassRule
public static HoverflyRule hoverflyRule = HoverflyRule.inSimulateMode(empty())

@Test
public void shouldCompletePurchaseWhenFraudCheckPasses() {
  // Given
  hoverflyRule.simulate(dsl(
    service("www.payments.com")
        .post("/api/bookings")
        .body(json(new Payment("foo")))
        .willReturn(success(json(new PaymentConfirmation(1)))),
    service("www.fraud.com")
        .get("/api/fraud/")
        .query("?foo=bar")
        .willReturn(success())
  ));

  // When
  someMethodUnderTest()
 
  // Then
  someAssertion()
}
```

Or with other languages, you can just use the API directly and do:

`PUT <hoverfly-host>:<hoverfly-admin-port>/api/v2/simulation <simulation-json>`

To set the data the at any time (i.e between tests)

I think this is synonymous to a 'programmable mode'.

If you want to be able to record  a journal, that could be something we introduce. At first I thought:

`hoverctl mode capture --journal`

But now I am thinking, maybe always write to a journal. It's easily transformed into a simulation (last matcher wins)? 

One problem I foresee is that when you do have a journal, and there's lots of requests, it would be hard to look through all captured requests and responses, and cherry pick which ones you need for each test. How would you want to do this?

**Comment by benjih** [comment] 2017-02-15 15:43
Hey @paul-hammant,

(v0.10.1)[https://github.com/SpectoLabs/hoverfly/releases/tag/v0.10.1] of Hoverfly has just been released which includes the bug fix I mentioned earlier in this ticket regarding the request bodies on POST/PUT requests not properly being proxied through to your Python application in test.

**Comment by ph-ms** [comment] 2017-02-15 15:46
Great work, thanks!

**Comment by JohnFDavenport** [comment] 2017-08-25 10:22
Closing this. I'm also going to lock it as it is a composite issue and confusing. Please open new issues and cross-reference if we've missed something.

**Closed by JohnFDavenport** 2017-08-25 10:22 UTC
