### ISSUE TITLE
Eager caching not behaving as anticipated.

### ISSUE THREAD

**Issue by colts45s** [SpectoLabs/hoverfly#1002] opened 2022-01-27 20:58 UTC
## Steps to reproduce the issue
1. Start Hoverfly in capture mode
2. Run traffic through the proxy and capture both request and responses
3. Export configuration.json
4. Stop Hoverfly
5. Start Hoverfly in Simulation mode (Found webserver and proxy to behave identically)
6. Import configuration
7. Check cache. 

### Observed result
**None**
```
Cache is null
```

## Expected result
Cache populated with the configuration data in an eager fashion rather than lazy loading

## Additional relevant information
1. Hoverfly version: 1.3.0
2. I found the same behavior if switching from capture to simulate in the same instance. To get a cached request response pair I would have to execute the call in capture, change to simulation, then re-run the request to populate the cache.

**Comment by tommysitu** [comment] 2022-02-07 20:22
@colts45s this is a bug actually, so what happens is that the eager caching function is only called when you run `hoverctl mode simulate`, but it's not executed when hoverfly starts 🤦 

The workaround is that after step 5 in your example, you call `hoverctl mode simulate` and it should force the cache preloading.

**Comment by colts45s** [comment] 2022-02-08 19:36
I attempted this work around and was unable to achieve eager caching, I have a valid configuration.json file and even after i explicitly set the mode to simulate, loading the configuration does not add any items to the cache.

**Comment by tommysitu** [comment] 2022-02-08 20:42
ok, the problem is this function checks eagerly cacheable simulation always return nil 😞 
https://github.com/SpectoLabs/hoverfly/blob/master/core/models/request_matcher.go#L207

**Comment by tommysitu** [comment] 2022-02-08 23:49
https://github.com/SpectoLabs/hoverfly/pull/1006 should fix the workaround at least

**Comment by kapishmalik** [comment] 2023-03-12 13:52
@colts45s raised PR to fix this issue.

**Comment by kapishmalik** [comment] 2023-03-17 03:46
@colts45s this is done. You can check and let us know incase of any concerns.

**Comment by kapishmalik** [comment] 2023-03-18 18:16
@tommysitu you can close this issue.

**Comment by tommysitu** [comment] 2023-11-28 22:32
This has been fixed since https://github.com/SpectoLabs/hoverfly/releases/tag/v1.5.2

**Closed by tommysitu** 2023-11-28 22:32 UTC
Labels: bug
