### ISSUE TITLE
Hoverctl status

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly#584] opened 2017-06-08 14:00 UTC
Suggestion, but could it be useful to have a `hoverctl status` command that gives you all the information about the target Hoverfly, such as ports, mode etc?

**Comment by benjih** [comment] 2017-06-08 16:51
Closing as this is a duplicate of https://github.com/SpectoLabs/hoverfly/issues/351

**Closed by benjih** 2017-06-08 16:51 UTC
