### ISSUE TITLE
Problem setting up hoverfly behind AWS ELB

### ISSUE THREAD

**Issue by yougusnc** [SpectoLabs/hoverfly#562] opened 2017-05-29 16:03 UTC
Hi, 

I have put hoverfly on an AWS EC2 instance as proxy server in modify mode, and it would work if my toy app directly use its 8500 port. To make future life easier, I tried to put an AWS load balancer (ELB) in front of it, and I tried to open ELB port 8500 and forward to hoverfly 8500 port. When I tried to use the ELB url as the proxy host, it does not work by saying something like "unsupported proxy protocol ...."

I first found out that proxy protocol is not open on ELB by default, so I followed the [instruction from AWS about enabling the proxy protocol](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html) to enable it on the ELB, and I can verify using describe ELB aws command that the it is installed and backend distribution to http port 8500 is set up as well (basically all steps has been down and I can see proxy protocol in ELB detail description), so the setup is 
`ELB listener: HTTP port 8500, distribute to HTTP port 8500 of hoverfly.'

Then I tried it again, but get error message below
`"I/O error on GET request for \"https://gturnquist-quoters.cfapps.io/api/random\": Unable to tunnel through proxy. Proxy returns \"HTTP/1.1 400 BAD_REQUEST\"; nested exception is java.io.IOException: Unable to tunnel through proxy. Proxy returns \"HTTP/1.1 400 BAD_REQUEST\""` 

I kind of suspect that it is an ELB issue, but since it is such a generic setup, I wonder whether someone has tried the same kind of setup (AWS ELB in front of hoverfly). I would really appreciate if someone can point out what is wrong...

**Comment by mogronalol** [comment] 2017-05-30 09:47
@yougusnc I may be wrong but I would imagine that the ELB is working as a reverse not a forward proxy like Hoverfly. The other issue could be to do with the http connect method, which forward proxies use for SSL. It's likely this isn't supported by the ELB. This is probably beyond the scope of Hoverfly, but we do have a cloud version which is in private beta. Would this be something you'd be interested in trying?

**Comment by yougusnc** [comment] 2017-05-30 16:04
@mogronalol Andrew, you could be right but then how would hoverfly work behind an AWS ELB then? The down side of not having ELB in front of it is obvious, if the AWS task was restarted, it could have a new ip / host url, then all projects that uses this stand-alone instance as proxy has to change config files...

Most 3rd party / clients we work with are financial institutes, all traffic with them is strictly HTTPS, and I was trying to see whether I can use a stand-alone hoverfly instance as a stepping stone between our own services and the 3rd party services. For the private beta you mentioned, I am interested from the pure tech point of view, but it is unlikely that we can get approval from those 3rd parties and auditors to go through an outside server proxy with their QA / UAT credentials. 

I now has some limited user experience with my user case, maybe I can propose something for more consideration: Maybe enable the capture mode and modify mode even for hoverfly running as a web server. 
1.) Running as a web server, ELB issue is resolved.
2.) Running as a web server, for HTTPS traffic, I don't have to import a ca.pem (even if it is generated by our own hoverfly instance) into the keystore (for java) or some other mechanism of PHP / node js, etc. This step itself would have a lot of resistance from the devOp team because it means one more secrete for them and one more if / then in their server building scripts for various environments. 
3). The interface could be something like https://my.hoverfly.server/proxy?endpoint=encoded_original_destination_url and it just pass all http method / headers / body / other parameters, etc to the original url and pass back the result, basically doing a proxy without the proxy protocol... not sure whether it would have any side-effect.
4). For a strictly regulated industry, maybe a premium edition with premium features as hosted solution would have an easier chance to get in when compared with a cloud edition. 
5). Doing it this way it is a cleaner configuration in the application too, it's just an end-point url configuration change instead of changing things like java proxy start up flag that would affects all traffic or doing code change to those specific endpoints.

Just some thoughts from my limited experience.

**Comment by mogronalol** [comment] 2017-05-30 16:27
@yougusnc Thanks for the useful feedback.

Although the private beta is a public SaaS (Which is https only), we are also aiming to provide dedicated instances (these would run within a customer's AWS VPC or Google Cloud Private Network). We then plan on having another step up above that which would be on-premise installations in a users data centre. This would abstract away a lot of the operational complexity involved in load balancing forward proxies which support SSH, which is actually quite tricky for the above-mentioned reasons. We're happy to talk more about this if it raises any interest at your end.

My suggestion would be the same as yours, which would be to run Hoverfly in web server mode, so it would act as a reverse proxy rather than forward. Of course on our side forward and reverse should have feature parity which right now they don't (But they will). Until that happens you won't be able to capture as you have mentioned. Ideally, we want the only trade-off to be a proxy configuration vs a url change.

I don't see a workaround for certificates, you would always want to have it use your own CA, otherwise people could MITM attack each other - unless I missed something?

Finally, the only other option is to go down a network layer and use a TCP load balancer, which could also work as it doesn't know about http. I think you can do this with ELB?

**Comment by yougusnc** [comment] 2017-05-30 18:19
For TCP proxy on ELB, I tried that too but got the same error back... I'll try to play with that again just in case something was not set correctly.

If it is a web server, there is no need for work around for the certificate. Because for the app that uses it, https://my.hoverfly.server/proxy?endpoint=encoded_original_destination_url , is THE end point of that service. I just need to get a domain name of my.hoverfly.server setup, and get a proper SSL certificate for it from AWS or other CA vendor, I don't need a CA to sign and say this is from "https://my.3rdparty.com". This is a man-in-the-middle server that I told my server to trust because it is our own server but it does not need to claim it as a different server. I don't think it can be done for a proxy protocol server, given the modify / syth mode.

**Comment by mogronalol** [comment] 2017-05-31 10:27
Okay, I understand. Yes, that does make sense - as your web server certificate can be signed by a trusted CA. I like the URL approach, but there's a risk it could clash with the real request query. So the other option could be a custom `X-Hoverfly-Forward-To-Host` or similar?

Let me know how you get on with this, we are always interested feedback.

**Comment by mogronalol** [comment] 2017-08-15 13:12
It's not just AWS, I think you will find that a lot of load balancers don't support CONNECT method. It's unfortunate but there's nothing really we can do at our end, other than suggest using our SaaS which will be released shortly, or run it in web server once we have implemented the ability for it to capture traffic in that mode as well as simulate. I will close this issue now as the problem is not Hoverfly.

**Closed by mogronalol** 2017-08-15 13:12 UTC
